[config]
varbool = true
variant_name = "_pasta"
variant_tname = "Pasta"
xl_dir_path = "D:/x4_extract_2.6/assets/units/size_xl/macros"
l_dir_path = "D:/x4_extract_2.6/assets/units/size_l/macros"
m_dir_path = "D:/x4_extract_2.6/assets/units/size_m/macros"
s_dir_path = "D:/x4_extract_2.6/assets/units/size_s/macros"
ware_path = "D:/x4_extract_2.6/libraries/wares.xml"
t_path = "D:/x4_extract_2.6/t/0001-l044.xml"
out_path ="C:/Users/alby/Desktop/tpwar_targets/tpwar_ship_target/"
mod_name = "Extensions\\Rust Output\\macros"
# t
pageid = "20957250"

#racial faction deff
[faction_vec]
argon = ["argon", "antigone", "agi", "goner", "wholefood", "ledda", "aldrin", "cantera", "toride", "jonferson", "plutarch", "terracorp", "beryll", "fred", "terrapmc", "otas", "terrans","yaki","usc","heartofalbion","sonraenergy"]
teladi = ["teladi", "ministry", "telunion","nmmc", "atreus", "ptni", "franton", "chow", "uguras" ]
paranid = ["paranid", "holyorder", "buccaneers","heretics"]
xenon = ["xenon", "xenonmatrix"]
khaak = ["khaak", "khaakpox"]
pirates = ["scaleplate", "hatikvah", "atlas", "sovsyn" , "cartel", "strongarms", "plutarch","terracorp", "beryll", "terrapmc", "reivers", "nolimits", "uguras","yaki"]


#TODO
# - write an explanantion of the physics properties
# - determinism for people, hangarcapacity, ammo

# while it is possible to add production cost, 
# the effects would have to be seriously considered 
# and not the result of some random function

# no decimals! 
# (a..b) * purposemod of shiptype 

# this is largely irrelevant to what numbers you might select 
# but I wrote the note to us here and here it stays:
 
# the result of a range will be refered to as n
# cargo, hull, mass, are first order values. 
# these values use purposemod to modify which one 
# starts the chain of calculation
# first order values return n. 
# n > average sets the average of the next calculation 
# as the max of the next range. 
# n < average sets the average of the next calculation 
# as the min of the next range. 
# !!! note: mass has an inverse relationship to the other first order values 
# so reverse the logic above for mass 

# trade_purposemod example:
# cargo = n
# mass = n inversely bounded by the result of cargo n 
# hull = n is ALSO inversely bounded by the result of mass
# second order stuff like: unit, ammo, explosion 
# follow the same order for all purpose/class. 




[xl_config]
#purpose
trade_purposemod = 2.0
fight_purposemod = 2.0
build_purposemod = 0.5
mine_purposemod = 1.0
auxiliary_purposemod= 1.8
#wareprice
min = [10000000,15000000]
average = [15000000, 22000000]
max = [22000000,35000000]
#physics - min and max CANNOT be the same value
mass= [549, 1500]
i_pitch= [400, 900]
i_yaw= [400, 900]
i_roll= [400, 900]
forward= [400, 900]
reverse= [400, 900]
horizontal= [200, 500]
vertical= [200, 500]
d_pitch= [100, 810]
d_yaw= [100, 810]
d_roll= [100, 810]
#stats
explosion = [500000, 1500000]
ammo = [500, 5000]
unit = [20, 80]
hull = [80000, 250000]
cargo = [12000, 50000]
people = [200, 1000]
#hanagar capacity [s,m]
hangarcapacity = [10, 40 ,1, 10]
[l_config]
#purpose
trade_purposemod = 2.0
fight_purposemod = 2.0
build_purposemod = 0.5
mine_purposemod = 1.0
auxiliary_purposemod= 1.8
#wareprice
min = [5000000,6000000]
average = [6000000, 7000000]
max = [7000000,10000000]
#physics - min and max CANNOT be the same value
mass= [200, 600]
i_pitch= [100, 200]
i_yaw= [100, 200]
i_roll= [100, 200]
forward= [100, 200]
reverse= [100, 200]
horizontal= [75, 200]
vertical= [75, 200]
d_pitch= [75, 300]
d_yaw= [75, 300]
d_roll= [75, 300]
#stats
explosion = [100000, 200000]
ammo = [100, 1000]
unit = [10, 50]
hull = [40000, 150000]
cargo = [8000, 35000]
people = [60, 200]
#hanagar capacity [s,m]
hangarcapacity = [5, 20 ,1, 5]
# small = 10
# medium = 10
[m_config]
#purpose
trade_purposemod = 2.0
fight_purposemod = 2.0
build_purposemod = 0.5
mine_purposemod = 1.0
auxiliary_purposemod= 1.8
#wareprice
min = [1000000,1500000]
average = [1500000, 2000000]
max = [2000000,2500000]
#physics - min and max CANNOT be the same value
mass= [20, 50]
i_pitch= [5, 9]
i_yaw= [5, 9]
i_roll= [5, 9]
forward= [4, 10]
reverse= [25, 35]
horizontal= [10, 25]
vertical= [10, 25]
d_pitch= [5, 20]
d_yaw= [5, 20]
d_roll= [5, 20]
#stats
explosion = [20000, 50000]
ammo = [50, 200]
unit = [5, 15]
hull = [10000, 35000]
cargo = [3000, 12000]
people = [10, 50]
#hanagar capacity [s,m]
hangarcapacity = [1, 5 ,1, 10]
# small = 10
# medium = 10
[s_config]
#purpose
trade_purposemod = 2.0
fight_purposemod = 2.0
build_purposemod = 0.5
mine_purposemod = 1.0
auxiliary_purposemod= 1.8
#wareprice
min = [200000,300000]
average = [300000, 500000]
max = [500000,600000]
#physics - min and max CANNOT be the same value
mass= [2, 12]
i_pitch= [2, 4]
i_yaw= [2, 4]
i_roll= [2, 4]
forward= [4, 8]
reverse= [15, 30]
horizontal= [2, 5]
vertical= [2, 5]
d_pitch= [2, 5]
d_yaw= [2, 5]
d_roll= [2, 5]
#stats
explosion = [3000, 5000]
ammo = [5, 30]
unit = [1, 5]
hull = [3000, 10000]
cargo = [200, 500]
people = [1, 15]
#hanagar capacity [s,m]
hangarcapacity = [10, 40 ,1, 10]
# small = 10
# medium = 10

     
